# Generated by Django 5.2.3 on 2025-11-29 01:13

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, storage=config.storage_backends.MinioMediaStoragePrivateTesting(), upload_to='invoices/'),
        ),
    ]
