# Generated by Django 5.2.3 on 2025-11-29 01:41

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=config.storage_backends.MinioMediaStoragePrivateTesting(), upload_to='invoices/'),
        ),
    ]
