# Generated by Django 5.2.3 on 2025-11-29 03:17

import accounts.models
import config.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=config.storage_backends.MinioMediaStoragePrivateTesting(), upload_to=accounts.models.user_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])]),
        ),
    ]
